# Build Container Image with the latest tag
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/edm-events-scraper:latest', '.']

# Push the container image to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/edm-events-scraper:latest'

options:
  logging: CLOUD_LOGGING_ONLY